//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 DwgDesign.rc 使用
//
#define IDS_PROJNAME                    100
#define IDC_TAB1                        100
#define IDC_TAB                         100
#define IDD_DLG_MAIN                    102
#define IDD_DLG_DISCERN                 103
#define IDC_BTN_SELECTBLOCK             103
#define IDD_DLG_DL                      104
#define IDC_EDIT_PATH_DQTX              105
#define IDD_DLG_EDITBLOCK               105
#define IDC_EDIT_PATH_JXB               106
#define IDD_DLG_EDITDL                  106
#define IDC_BTN_DQTX                    107
#define IDD_DLG_AUTOCREAT               107
#define IDC_BTN_JXB                     108
#define IDD_DLG_WEIHAO                  108
#define IDC_STATIC_NUM                  109
#define IDD_DLG_PPSJ                    109
#define IDC_BTN_CREATMARK               110
#define IDC_BTN_CRETEJXB                111
#define IDD_DLG_LJQ                     111
#define IDC_STATIC_NAME                 112
#define IDC_LIST_INFO                   113
#define IDC_BTN_CHECKINFO               113
#define IDD_DLG_DLGG                    113
#define IDC_BTN_REFLIST                 114
#define IDC_CMB_L1                      115
#define IDD_DLG_DLFJ                    115
#define IDC_CMB_L2                      116
#define IDC_CMB_L3                      117
#define IDC_CMB_TH                      117
#define IDC_STATIC_VIEW                 118
#define IDD_DLG_ACCESSORY               118
#define IDC_CMB_DLGG                    119
#define IDC_CMB_DYDJ                    120
#define IDC_STATIC_MAIN                 121
#define IDC_STATIC_PIC                  122
#define IDC_CHECK_JX                    123
#define IDC_EDIT1                       124
#define IDC_EDIT2                       125
#define IDC_BTN_SELECTPATH              125
#define IDC_EDIT3                       126
#define IDC_EDIT_EXCELPATH              126
#define IDC_BTN_TABTOMARK               127
#define IDB_BITMAP2                     127
#define IDC_EDIT_CPMC                   127
#define IDC_LIST_WEIHAO                 128
#define IDB_BITMAP3                     128
#define IDC_EDIT_SHS                    128
#define IDC_BTN_AUTOWH                  129
#define IDB_BITMAP4                     129
#define IDC_EDIT_XMJD                   129
#define IDC_BTN_CHECKWH                 130
#define IDB_BITMAP1                     130
#define IDC_EDIT_GZJ                    130
#define IDC_EDIT_W                      131
#define IDC_EDIT_BM                     132
#define IDC_CMB_DLLX                    133
#define IDC_CMB_DLLJ                    134
#define IDD_DIALOG1                     134
#define IDC_BTN_SEARCH1                 135
#define IDD_DIALOG2                     135
#define IDC_LIST_LJQ                    136
#define IDD_DIALOG3                     136
#define IDD_DLGJSWZ                     136
#define IDC_BTN_SEARCH2                 137
#define IDC_BTN_SEARCH3                 138
#define IDD_DLG_FRAME                   138
#define IDC_LIST_FJ                     139
#define IDC_BTN_CREATDL                 140
#define IDC_EDIT_DLGG                   141
#define IDR_MENU2                       141
#define IDC_LIST_DLGG                   142
#define IDC_BUTTON1                     143
#define IDR_MENU3                       143
#define IDC_LIST1                       144
#define IDC_BUTTON2                     144
#define IDC_EDIT_DLLJGXB                145
#define IDC_BTN_SELECT                  146
#define IDR_MENU1                       146
#define IDC_EDIT_LJQMC                  147
#define IDD_DLG_PROMPT                  147
#define IDC_CMB_LJQLX                   148
#define IDD_DLG_HBTAB                   148
#define IDC_CMB_FJLX                    149
#define IDD_DLG_LHXX                    149
#define IDC_EDIT_FJMC                   150
#define IDD_DLG_VIEW                    150
#define IDC_EDIT_DLMC                   151
#define IDR_MENU4                       151
#define IDC_LIST_RESULT                 152
#define IDD_DLG_ITEMSELECT              152
#define IDD_DLGPRORESS                  153
#define IDC_RADIO_YCL                   154
#define IDD_PR                          154
#define IDD_PRORESS                     154
#define IDC_RADIO_WCL                   155
#define IDC_RADIO_ZH                    156
#define IDC_BTN_MXB                     157
#define IDC_BTN_DLMXB                   158
#define IDC_CMB_VIEW                    159
#define IDC_BTN_SETVIEW                 160
#define IDC_EDIT_MOD                    161
#define IDC_CMB_FOLDER                  163
#define IDC_CMB_DW                      165
#define IDC_CMB_WH                      166
#define IDC_EDIT_NUM                    167
#define IDC_EDIT_DH                     168
#define IDC_EDIT_MC                     169
#define IDC_EDIT_SEARCH                 170
#define IDC_BTN_INSERTFJ                171
#define IDC_RADIO_RU                    172
#define IDC_RADIO_RD                    173
#define IDC_RADIO_LU                    174
#define IDC_RADIO_LD                    175
#define IDC_CHECK_CONNECT               176
#define IDC_EDIT_GGXH                   177
#define IDC_BTN_CREATTAB                178
#define IDC_BTN_RESTOREDWG              179
#define IDC_BTN_CHECKDWG                180
#define IDC_STATIC_PREVIEW              181
#define IDC_CHECK1                      182
#define IDC_CHECK_LH                    182
#define IDC_RICHEDIT21                  184
#define IDC_RICHEDIT2_UPDATE            184
#define IDC_TREE1                       185
#define IDC_COMBO_TF                    186
#define IDC_EDIT_CPBH                   187
#define IDC_EDIT_XMDJ                   188
#define ID_ADD_PATH                     189
#define IDC_BTN_SJ1                     189
#define ID_JS_ADD                       190
#define IDC_BTN_SJ2                     190
#define ID_JS_DELETE                    191
#define IDC_BTN_SJ3                     191
#define ID_JS_EDIT                      192
#define IDC_BTN_SJ4                     192
#define ID_COPY                         193
#define IDC_STATIC_PPXX                 193
#define ID_PASTE                        194
#define IDC_LIST_YXFJ                   194
#define IDR_POPUP_MENU                  195
#define IDC_BTN_REFRESH                 195
#define IDR_MENU_EDIT                   196
#define IDC_BTN_HBTAB                   196
#define IDC_PROGRESS1                   197
#define IDC_BTN_JS                      198
#define IDC_EDIT_DLSJB                  199
#define IDC_EDIT_YQJ                    200
#define IDC_STATIC_FJXZ                 201
#define IDC_STATIC_YXFJ                 202
#define IDC_BUTTON_CONNECTSELECT        205
#define IDC_EDIT_PATH_ZJYS              206
#define IDC_BTN_ZJYS                    207
#define IDC_BTN_HIGHTLIGHT              208
#define IDC_BTN_UNHIGHTLIGHT            209
#define IDC_BTN_MAPCHECK                210
#define IDC_BUTTON3                     212
#define IDC_TREE                        213
#define IDC_TREE_SELECT                 213
#define IDC_EDIT_MANUALWEIHAO           214
#define IDC_BTN_MANUALINSERT            215
#define ID_32769                        32769
#define ID_32770                        32770
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_MENU                         32773
#define ID_MENU4                        32774
#define ID_32775                        32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         216
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
